import type { Metadata } from "next";
import { cn } from "../lib/utils";
import { bungee, changa } from "../lib/fonts";
import "./globals.css";
import Layout from "./components/layout-head-foot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          bungee.variable,
          changa.variable,
          changa.className,
          "font-normal antialiased"
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
